### ISSUE TITLE
Automation tooling around generating developer documention

### ISSUE THREAD

**Issue by guzman-raphael** [datajoint/datajoint-labbook#110]
- Using sphinx, some sort of extension for mozilla, etc.

**Comment by Synicix** [comment]
https://github.com/mozilla/sphinx-js

**Comment by Synicix** [comment]
Seems that this doesn't work out of the box, going to try to keep at it and see if I can figure out why... But yeah seems that type script support for this is still iffy

**Comment by Synicix** [comment]
Yeah it seems that typescript support is very iffy with sphinx-js, however using typedoc directly generate a decent web page and it just works. So I guess for now we should stic with typedocs.
![image](https://user-images.githubusercontent.com/10690095/110188476-6b862880-7de1-11eb-9b53-29b6547be9a8.png)
![image](https://user-images.githubusercontent.com/10690095/110188484-7345cd00-7de1-11eb-865c-9aa3b1c4497d.png)
