### ISSUE TITLE
Add support to scroll within tables to view all entries (Safari browser)

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-labbook#146]
### Problem
When using the Safari browser on MacOS, there isn't an option to scroll to see all entries within a table. 

### Requirements
With Google Chrome, the scroll bar is present.  Would like the scrolling feature to mirror Google Chrome.

### Alternative Considerations
As Google Chrome is the only browser currently recommended, as validation or development have not been performed for any other browser yet, could we please make a note of this in the `User Documentation`?

- OS: MacOS 11.2.3
- DataJoint LabBook Version: 0.1.0
- MySQL Version: Ver 15.1 Distrib 10.5.6-MariaDB (local) or Ver 14.14 Distrib 5.7.33 (remote)
- MySQL Deployment Strategy:  local-native or remote

**Comment by Synicix** [comment]
Oh, this was already address in #142 quite a while ago. This is mostly due to Safari requires us to add some webkit prefix cause they want to be special. I recommend using that branch until we can get it merged into dev and cut a new release.

**Comment by kabilar** [comment]
Closing as this is not a priority for me.
