### ISSUE TITLE
Loading preview of big tables takes long and ended up with some error

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-labbook#147]
### Description
When loading a big table, it takes long to process and ended up with the following error:
```
Problem fetching table content: Error: 401 - UNAUTHORIZED: (Signature verification failed)
```

### Reproducibility
I have seen this error on two databases:
princeton and IBL internal. It is easier for developers to use IBL internal to replicate the error. The table I was trying to load was `ibl_behavior.TrialSet.Trial`.

In ibl public database, previewing table `ibl_behavior.TrialSet.Trial` also returns an error. Not sure this is the same issue or a different one.
```
Problem fetching table content: SyntaxError: Unexpected token N in JSON at position 518
```

**Comment by Synicix** [comment]
Turns on this is an issue with json handling Nans and infs. This will be patch shortly
