### ISSUE TITLE
Freeze attribute names in the `View Content` tab

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-labbook#148]
### Problem
The attribute names are visible at the top of the `View Content` tab.  However, when I scroll down to view all entries within a table, the attribute names are not shown.

### Requirements
It would be a nice addition to freeze the attribute names at the top of the screen, under the table name, so that they are visible when scrolling down to view all table entries.

OS: MacOS 11.2.3
DataJoint LabBook Version: 0.1.0
MySQL Version: Ver 15.1 Distrib 10.5.6-MariaDB (local) or Ver 14.14 Distrib 5.7.33 (remote)
MySQL Deployment Strategy: local-native or remote

**Comment by Synicix** [comment]
Yeah that was one of the features we are looking to implement in the next round of features to add. Will update this accordingly.

**Comment by kabilar** [comment]
Closing as this is no longer a priority for me.
