### ISSUE TITLE
Reset `View Content` tab when navigating between schemas

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-labbook#149]
### Problem
When I navigate from table_A in schema_1 to schema_2, the contents of table_A are still visible in the `View Content` tab.

### Requirements
It would be ideal to have the `View Content` tab reset (see screenshot), when navigating between schemas.

OS: MacOS 11.2.3
DataJoint LabBook Version: 0.1.0
MySQL Version: Ver 15.1 Distrib 10.5.6-MariaDB (local) or Ver 14.14 Distrib 5.7.33 (remote)
MySQL Deployment Strategy: local-native or remote

### Screenshots
<img width="1552" alt="image1" src="https://user-images.githubusercontent.com/871137/118335204-59ed8b00-b4cc-11eb-8d68-9eb1f647ef02.png">

**Comment by Synicix** [comment]
We set the behavior to be like that until you click on another table. The logic behind this is just to leave what you already have on screen until there is a need to change it.
