### ISSUE TITLE
Add unit/integration testing

### ISSUE THREAD

**Issue by guzman-raphael** [datajoint/datajoint-labbook#80]
Add unit/integration testing using a standard framework compatible with React (such as `jest`).

**Comment by ChihweiLHBird** [comment]
@guzman-raphael I think I can start with writing the test cases and try to get familiar with the project. May I be assigned to this issue?

**Comment by guzman-raphael** [comment]
@ChihweiLHBird Awesome, thanks for the help. :handshake: You are now assigned.

**Comment by guzman-raphael** [comment]
@ChihweiLHBird I see you've signed up with an account with [DataJointIO](https://datajoint.io) which provides access to our tutorial database (`tutorial-db.datajoint.io`) using the same username/password. If so, you can use these details to login using `datajoint-labbook` to help you develop your tests. I've shared with you a simplistic `contributor_company` schema which should be sufficient to minimally test most merged features (below is a diagram of the pipeline). Have a look in the `Table Information` to understand the relationship between the tables.
![image](https://user-images.githubusercontent.com/38401847/108899676-4eca4380-75de-11eb-8e39-9ea1cc8507ff.png)

**Comment by guzman-raphael** [comment]
First tests added in #130. Integrated into CI in #140.
