### ISSUE TITLE
Hide check dependency logic

### ISSUE THREAD

**Issue by guzman-raphael** [datajoint/datajoint-labbook#83]
Hide check dependency logic and issue delete as insert/update (which will use delete quick on backend).
Add proper handling to expect error and display parsed body to user with error details (records that could not be deleted).

**Comment by guzman-raphael** [comment]
Depends on datajoint/pharus#86 being closed.

**Comment by Synicix** [comment]
Not sure why this got closed, since we still have to do it for update
